apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-ip-error
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nfs-ip-error
  template:
    metadata:
      labels:
        app: nfs-ip-error
    spec:
      containers:
      - image: hwchiu/netutils
        name: c1
        volumeMounts:
          - mountPath: "/c1"
            name: nfs-ip-demo
      volumes:
        - name: nfs-ip-demo
          persistentVolumeClaim:
            claimName: nfs-ip-demo
