apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.18.0.1
    path: /nfsshare
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-2
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.18.0.1
    path: /nfsshare
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-claim
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    name: force-nfs
    namespace: default
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.18.0.1
    path: /nfsshare
