apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-pending
  namespace: default
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5000Gi
