apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
spec:
  replicas: 120
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        commands:
          - "/bin/sleep"
          - "3600"
