apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-host
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-host
  template:
    metadata:
      labels:
        app: pod-host
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: pod-host-server
        image: hwchiu/netutils
      hostNetwork: true
