apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-none
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-none
  template:
    metadata:
      labels:
        app: pod-none
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: pod-none-server
        image: hwchiu/netutils
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 1.2.3.4
        searches:
          - ns1.svc.cluster.local
          - my.dns.search.suffix
        options:
          - name: ndots
            value: "5"
