apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hwchiu-role
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "services"]
  verbs: ["delete", "get", "list", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hwchiu-role-binding
roleRef:
  kind: ClusterRole
  name: hwchiu-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: hwchiu
  namespace: default
