apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveness-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liveness-demo
  template:
    metadata:
      labels:
        app: liveness-demo
    spec:
      containers:
      - name: python-demo-server
        image: hwchiu/netutils:python
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - curl
            - localhost:8000 
          initialDelaySeconds: 5
          periodSeconds: 5       
