apiVersion: apps/v1
kind: Deployment
metadata:
  name: readiness-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: readiness-demo
  template:
    metadata:
      labels:
        app: readiness-demo
    spec:
      containers:
      - name: python-demo-server
        image: hwchiu/netutils:python
        imagePullPolicy: Always
        readinessProbe:
          exec:
            command:
            - curl
            - localhost:8080
          initialDelaySeconds: 5
          periodSeconds: 5       
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-demo
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: readiness-demo
