apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-subpath-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-subpath-demo
  template:
    metadata:
      labels:
        app: config-subpath-demo
    spec:
      containers:
      - image: hwchiu/netutils
        name: c1
        volumeMounts:
          - mountPath: "/config"
            name: config-volume
          - mountPath: "/json"
            name: config-volume
            subPath: json.data
          - mountPath: "/yaml"
            name: config-volume
            subPath: yaml.config
          - mountPath: "/yaml_two"
            name: config-volume
            subPath: hmmm
      volumes:
      - name: config-volume
        configMap:
          name: config-test
