kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-mismatch-wihoutsc-demo
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
