apiVersion: v1
kind: Pod
metadata:
  name: clusterfirst-true
  labels:
    app: myapp
spec:
  containers:
  - name: clusterfirst
    image: hwchiu/netutils
  hostNetwork: true
  dnsPolicy: ClusterFirst
