apiVersion: v1
kind: Pod
metadata:
  name: clusterfirstwithhost
  labels:
    app: myapp
spec:
  containers:
  - name: clusterfirstwithhost
    image: hwchiu/netutils
  dnsPolicy: ClusterFirstWithHostNet
