apiVersion: v1
kind: Pod
metadata:
  name: pv-debug-server-2
spec:
  containers:
  - image: hwchiu/netutils
    imagePullPolicy: Always
    name: debug-server
    volumeMounts:
      - mountPath: /test
        name: data-pvc 
  volumes:
  - name: data-pvc
    persistentVolumeClaim:
      claimName: pvc-nfs-2
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-2
spec:
  storageClassName: "managed-nfs-storage"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
