apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-god
spec:
  replicas: 5
  selector:
    matchLabels:
      app: deployment-god
  template:
    metadata:
      labels:
        app: deployment-god
    spec:
      tolerations:
      - operator: Exists
        effect: NoSchedule
      containers:
      - name: deployment-god-server
        image: hwchiu/netutils 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-god
spec:
  selector:
    matchLabels:
      app: web-god
  replicas: 1
  template:
    metadata:
      labels:
        app: web-god
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: web-app
        image: nginx:1.16-alpine
