apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-vol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debug-vol
  template:
    metadata:
      labels:
        app: debug-vol
    spec:
      containers:
      - name: debug-server
        image: hwchiu/netutils
        volumeMounts:
        - name: secret-volume
          mountPath: /tmp/config
      volumes:
      - name: secret-volume
        secret:
          secretName: secret-test
