apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: debug-pod
spec:
  selector:
    matchLabels:
      app: debug-pod
  template:
    metadata:
      labels:
        app: debug-pod
    spec:
      containers:
        - name: debug-pod
          image: 172.17.8.111/hiskio/debug:latest
